name: Deploy Node.js App

on:
  push:
    branches:
      - master  # Trigger on push to master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH for EC2
        run: |
          mkdir -p ~/.ssh
          # Add the PEM key from GitHub secrets into the right location
          echo "${{ secrets.PROD_KEY }}" > ~/.ssh/id_rsa.pem
          chmod 600 ~/.ssh/id_rsa.pem
          ssh-keyscan -H ${{ secrets.PROD_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to production
        run: |
          # SSH into the server and run deployment commands
          ssh -i ~/.ssh/id_rsa.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.PROD_HOST }} << 'EOF'
              # Navigate to the directory of the app
              cd /home/ubuntu/app

              # Pull the latest code from GitHub
              git pull origin master

              # Install dependencies
              npm install

              # Make sure PM2 is installed globally
              sudo npm install -g pm2

              # Start the application using pm2 (or restart if already running)
              pm2 start app.js --name "myapp" || pm2 restart myapp

              # Save pm2 process list to ensure app restarts after reboot
              pm2 save
          EOF
